/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface FabButton {
        /**
          * Disabled
         */
        "disabled": boolean;
        /**
          * Font size in the button css property
         */
        "fontSize": string;
        /**
          * Height string property that will be passed in the width css property
         */
        "height": string;
        /**
          * The label of the button
         */
        "label": string;
        /**
          * Primary style
         */
        "primary": boolean;
        /**
          * Rounded style
         */
        "rounded": 'small' | 'medium' | 'large';
        /**
          * Width string property that will be passed in the width css property
         */
        "width": string;
    }
}
declare global {
    interface HTMLFabButtonElement extends Components.FabButton, HTMLStencilElement {
    }
    var HTMLFabButtonElement: {
        prototype: HTMLFabButtonElement;
        new (): HTMLFabButtonElement;
    };
    interface HTMLElementTagNameMap {
        "fab-button": HTMLFabButtonElement;
    }
}
declare namespace LocalJSX {
    interface FabButton {
        /**
          * Disabled
         */
        "disabled"?: boolean;
        /**
          * Font size in the button css property
         */
        "fontSize"?: string;
        /**
          * Height string property that will be passed in the width css property
         */
        "height"?: string;
        /**
          * The label of the button
         */
        "label"?: string;
        /**
          * Primary style
         */
        "primary"?: boolean;
        /**
          * Rounded style
         */
        "rounded"?: 'small' | 'medium' | 'large';
        /**
          * Width string property that will be passed in the width css property
         */
        "width"?: string;
    }
    interface IntrinsicElements {
        "fab-button": FabButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "fab-button": LocalJSX.FabButton & JSXBase.HTMLAttributes<HTMLFabButtonElement>;
        }
    }
}
